export type LogicalOperator = "AND" | "OR";

// Every `…Id` below holds the `id` of a facet, field or operator
// (docs/ARCHITECTURE.md, "Naming"); only a node's own `id` is made up by the
// frontend (tree.ts).
export interface Condition {
  kind: "condition";
  /** Generated by tree.ts; ties the row on screen (data-node-id) and its issues to this node. */
  id: string;
  /** The chosen facet's `Facet.id`, or null. With `fieldId`, names the
   *  field the condition targets. */
  facetId: string | null;
  /** The chosen field's own `Field.id` within that facet, or null. */
  fieldId: string | null;
  /** The chosen operator's `CatalogOperator.id` (e.g. "gt"), or null. */
  operatorId: string | null;
  /** Shaped by the operator's arity: nothing ("none"), one value, a [from, to]
   *  pair ("two") or a list ("many"). validate.ts checks it. */
  value: unknown;
}

export interface Group {
  kind: "group";
  id: string;
  operator: LogicalOperator;
  children: (Group | Condition)[];
  collapsed?: boolean;
}

export type QueryNode = Group | Condition;

/** Something that stops the query from running. Any issue blocks Run. */
export interface Issue {
  nodeId: string;
  message: string;
  /**
   * "incomplete": something the user simply hasn't filled in yet — shown as a
   * quiet hint. "invalid": the query refers to something that cannot work —
   * shown in red.
   */
  kind: "incomplete" | "invalid";
}
